### ISSUE TITLE
NPE when message from consumer is null

### ISSUE THREAD

**Issue by nickcaballero** [opentracing-contrib/java-jms#9]
NPE when message from consumer is null.

```
java.lang.NullPointerException: null
	at io.opentracing.contrib.jms.common.JmsTextMapExtractAdapter.<init>(JmsTextMapExtractAdapter.java:34) ~[opentracing-jms-common-0.0.5.jar:?]
	at io.opentracing.contrib.jms.common.TracingMessageUtils.extract(TracingMessageUtils.java:81) ~[opentracing-jms-common-0.0.5.jar:?]
	at io.opentracing.contrib.jms.common.TracingMessageUtils.buildFollowingSpan(TracingMessageUtils.java:53) ~[opentracing-jms-common-0.0.5.jar:?]
	at io.opentracing.contrib.jms.common.TracingMessageUtils.buildAndFinishChildSpan(TracingMessageUtils.java:42) ~[opentracing-jms-common-0.0.5.jar:?]
	at io.opentracing.contrib.jms.common.TracingMessageConsumer.finishSpan(TracingMessageConsumer.java:77) ~[opentracing-jms-common-0.0.5.jar:?]
	at io.opentracing.contrib.jms.common.TracingMessageConsumer.receive(TracingMessageConsumer.java:60) ~[opentracing-jms-common-0.0.5.jar:?]
	at org.springframework.jms.core.JmsTemplate.doReceive(JmsTemplate.java:836) ~[spring-jms-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.jms.core.JmsTemplate.doReceive(JmsTemplate.java:803) ~[spring-jms-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.jms.core.JmsTemplate.doReceive(JmsTemplate.java:784) ~[spring-jms-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.jms.core.JmsTemplate$10.doInJms(JmsTemplate.java:768) ~[spring-jms-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.jms.core.JmsTemplate$10.doInJms(JmsTemplate.java:764) ~[spring-jms-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:494) ~[spring-jms-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.jms.core.JmsTemplate.receiveSelected(JmsTemplate.java:764) ~[spring-jms-4.2.2.RELEASE.jar:4.2.2.RELEASE]
```

**Comment by malafeev** [comment]
fixed
